#!/usr/bin/env python3
"""
Test APA-0000619 Real Data Consolidation Fix (Issue #96)

This test uses the actual APA-0000619 data from the CSV file to verify that 
the cost-center-aware V-VC00048 skip logic correctly allows VCT cost center 
entries to get consolidated billing.

Based on the CSV data:
- APA-0000619 has two entries: 25.00 R-USD and 39.00 R-USD
- Both entries use vendor V-VC00048 (corporate credit card)
- Both entries have department VCT.1692G (VCT cost center)
- These should get consolidated billing, not be skipped
"""

import os
import sys
import json
import tempfile
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

def create_apa_0000619_real_data():
    """Create the exact APA-0000619 data from the CSV file."""
    return [
        {
            'voucher_no': 'APA-0000619',
            'description': 'VicOne Corporate Credit Card Saas Subscription',
            'Document_Date': '2025/07/16',
            'External_Document_No': 'APA-0000619',
            'debit': {
                'account': '76900-10',
                'gl_account': 'G/L Account',
                'amount': 25.00,
                'currency': 'R-USD',
                'department': 'VCT.1692G',
                'applicant_code': '10108',
                'Receipt/Invoice Note(明細)': 'Frontitude UX Writing Assistant paid trial: 2025-07-16 to 2025-08-16',
                'free_field': '* Frontitude UX Writing Assistant paid trial: 2025-07-16 to 2025-08-16\\n* Writer.com Team plan paid trial: 2025-07-16 to 2025-08-16'
            },
            'credit': {
                'account': '31200-10',
                'gl_account': 'Vendor',
                'vendor_code': 'V-VC00048',
                'amount': 25.00,
                'currency': 'R-USD',
                'department': 'VCT.1692G',
                'Remarks': '* Frontitude UX Writing Assistant paid trial: 2025-07-16 to 2025-08-16\\n* Writer.com Team plan paid trial: 2025-07-16 to 2025-08-16'
            }
        },
        {
            'voucher_no': 'APA-0000619',
            'description': 'VicOne Corporate Credit Card Saas Subscription',
            'Document_Date': '2025/07/16',
            'External_Document_No': 'APA-0000619',
            'debit': {
                'account': '76900-10',
                'gl_account': 'G/L Account',
                'amount': 39.00,
                'currency': 'R-USD',
                'department': 'VCT.1692G',
                'applicant_code': '10108',
                'Receipt/Invoice Note(明細)': 'Writer.com Team plan paid trial: 2025-07-16 to 2025-08-16',
                'free_field': '* Frontitude UX Writing Assistant paid trial: 2025-07-16 to 2025-08-16\\n* Writer.com Team plan paid trial: 2025-07-16 to 2025-08-16'
            },
            'credit': {
                'account': '31200-10',
                'gl_account': 'Vendor',
                'vendor_code': 'V-VC00048',
                'amount': 39.00,
                'currency': 'R-USD',
                'department': 'VCT.1692G',
                'Remarks': '* Frontitude UX Writing Assistant paid trial: 2025-07-16 to 2025-08-16\\n* Writer.com Team plan paid trial: 2025-07-16 to 2025-08-16'
            }
        }
    ]

def create_apa_0000619_consolidated_entry():
    """Create the consolidated entry that would be generated by CSV converter."""
    return {
        'voucher_no': 'APA-0000619',
        'description': 'VicOne Corporate Credit Card Saas Subscription',
        'Document_Date': '2025/07/16',
        'External_Document_No': 'APA-0000619',
        'debit': {
            'account': '76900-10',
            'gl_account': 'G/L Account',
            'amount': 64.00,  # 25.00 + 39.00
            'currency': 'R-USD',
            'department': 'VCT.1692G',
            'applicant_code': '10108',
            'Receipt/Invoice Note(明細)': 'Combined Frontitude and Writer.com subscriptions'
        },
        'credit': {
            'account': '31200-10',
            'gl_account': 'Vendor',
            'vendor_code': 'V-VC00048',
            'amount': 64.00,  # 25.00 + 39.00
            'currency': 'R-USD',
            'department': 'VCT.1692G',  # VCT cost center - key point
            'consolidated': True,  # This should NOT be skipped with the fix
            'original_entries_count': 2,
            'consolidation_note': 'Consolidated from 2 entries',
            'Remarks': 'Consolidated credit card charges for Saas subscriptions'
        }
    }

def test_apa_0000619_skip_logic():
    """Test that APA-0000619 consolidated entry is not skipped by the new logic."""
    print("Testing APA-0000619 skip logic with real data...")
    
    consolidated_entry = create_apa_0000619_consolidated_entry()
    
    # Apply the new cost-center-aware skip logic
    is_v_vc00048_consolidated = (
        consolidated_entry.get("credit", {}).get("consolidated") == True and 
        consolidated_entry.get("credit", {}).get("vendor_code") == "V-VC00048"
    )
    
    department = consolidated_entry.get("credit", {}).get("department", "")
    cost_center = department[:3] if department else ""
    
    should_skip = is_v_vc00048_consolidated and cost_center != "VCT"
    
    print(f"  Voucher: {consolidated_entry.get('voucher_no')}")
    print(f"  Vendor: {consolidated_entry.get('credit', {}).get('vendor_code')}")
    print(f"  Department: {department}")
    print(f"  Cost Center: {cost_center}")
    print(f"  Is V-VC00048 consolidated: {is_v_vc00048_consolidated}")
    print(f"  Should be skipped: {should_skip}")
    print(f"  Amount: {consolidated_entry.get('credit', {}).get('amount')}")
    
    if not should_skip:
        print("  ✅ APA-0000619 will get consolidated billing (CORRECT)")
        return True
    else:
        print("  ❌ APA-0000619 will be skipped (INCORRECT - should get consolidated billing)")
        return False

def test_apa_0000619_workflow_simulation():
    """Simulate the complete workflow for APA-0000619."""
    print("Simulating complete APA-0000619 workflow...")
    
    # Step 1: Original entries from CSV
    original_entries = create_apa_0000619_real_data()
    print(f"  Step 1: CSV has {len(original_entries)} original entries")
    
    # Step 2: CSV converter creates consolidated entry
    consolidated_entry = create_apa_0000619_consolidated_entry()
    print(f"  Step 2: CSV converter creates consolidated entry")
    
    # Step 3: Process japan exports applies skip logic
    group_entries = [consolidated_entry]  # Simulate processing this group
    
    v_vc00048_consolidated_entries_to_skip = []
    
    for entry in group_entries:
        is_v_vc00048_consolidated = (
            entry.get("credit", {}).get("consolidated") == True and 
            entry.get("credit", {}).get("vendor_code") == "V-VC00048"
        )
        
        if is_v_vc00048_consolidated:
            department = entry.get("credit", {}).get("department", "")
            cost_center = department[:3] if department else ""
            
            # NEW LOGIC: Only skip if cost center is NOT VCT
            if cost_center != "VCT":
                v_vc00048_consolidated_entries_to_skip.append(entry)
                print(f"  Step 3: Skipping V-VC00048 entry for NON-VCT cost center {cost_center}")
            else:
                print(f"  Step 3: Keeping V-VC00048 entry for VCT cost center {cost_center}")
    
    entries_to_process = [e for e in group_entries if e not in v_vc00048_consolidated_entries_to_skip]
    
    print(f"  Result: {len(entries_to_process)} entries will be processed for API calls")
    print(f"  Result: {len(v_vc00048_consolidated_entries_to_skip)} entries will be skipped")
    
    # Verify expected behavior
    if len(entries_to_process) == 1 and len(v_vc00048_consolidated_entries_to_skip) == 0:
        print("  ✅ APA-0000619 consolidated entry will be processed (get consolidated billing)")
        return True
    else:
        print("  ❌ APA-0000619 consolidated entry will not be processed correctly")
        return False

def test_original_vs_new_behavior():
    """Compare the original behavior vs new behavior for APA-0000619."""
    print("Comparing original vs new behavior for APA-0000619...")
    
    consolidated_entry = create_apa_0000619_consolidated_entry()
    
    # Original behavior (blanket skip all V-VC00048 consolidated entries)
    is_v_vc00048_consolidated = (
        consolidated_entry.get("credit", {}).get("consolidated") == True and 
        consolidated_entry.get("credit", {}).get("vendor_code") == "V-VC00048"
    )
    
    original_would_skip = is_v_vc00048_consolidated
    
    # New behavior (cost-center-aware skip)
    department = consolidated_entry.get("credit", {}).get("department", "")
    cost_center = department[:3] if department else ""
    new_would_skip = is_v_vc00048_consolidated and cost_center != "VCT"
    
    print(f"  Original behavior would skip: {original_would_skip}")
    print(f"  New behavior would skip: {new_would_skip}")
    
    if original_would_skip and not new_would_skip:
        print("  ✅ Fix correctly changes behavior for APA-0000619")
        print("  ✅ VCT cost center entries now get consolidated billing")
        return True
    else:
        print("  ❌ Fix does not change behavior correctly")
        return False

def test_log_message_verification():
    """Test that the correct log messages would be generated."""
    print("Testing log message generation...")
    
    consolidated_entry = create_apa_0000619_consolidated_entry()
    
    is_v_vc00048_consolidated = (
        consolidated_entry.get("credit", {}).get("consolidated") == True and 
        consolidated_entry.get("credit", {}).get("vendor_code") == "V-VC00048"
    )
    
    if is_v_vc00048_consolidated:
        department = consolidated_entry.get("credit", {}).get("department", "")
        cost_center = department[:3] if department else ""
        voucher_no = consolidated_entry.get('voucher_no')
        amount = consolidated_entry.get('credit', {}).get('amount', 0)
        
        if cost_center != "VCT":
            expected_log = f"Skipping V-VC00048 consolidated entry for NON-VCT cost center {cost_center} - Voucher: {voucher_no}, Amount: {amount}"
            print(f"  Would log: {expected_log}")
        else:
            expected_log = f"Keeping V-VC00048 consolidated entry for VCT cost center {cost_center} - Voucher: {voucher_no}, Amount: {amount}"
            print(f"  Would log: {expected_log}")
            
            # This should match what we saw in the actual log
            if "Keeping V-VC00048 consolidated entry for VCT cost center VCT" in expected_log:
                print("  ✅ Log message confirms APA-0000619 will be kept")
                return True
    
    print("  ❌ Log message does not confirm correct behavior")
    return False

def main():
    """Run all APA-0000619 specific tests."""
    print("=" * 80)
    print("APA-0000619 Real Data Consolidation Fix Test (Issue #96)")
    print("=" * 80)
    
    all_tests_passed = True
    
    # Test 1: Skip logic with real data
    print("\n1. Testing APA-0000619 skip logic with real data...")
    if not test_apa_0000619_skip_logic():
        all_tests_passed = False
    
    # Test 2: Complete workflow simulation
    print("\n2. Simulating complete APA-0000619 workflow...")
    if not test_apa_0000619_workflow_simulation():
        all_tests_passed = False
    
    # Test 3: Original vs new behavior
    print("\n3. Comparing original vs new behavior...")
    if not test_original_vs_new_behavior():
        all_tests_passed = False
    
    # Test 4: Log message verification
    print("\n4. Testing log message generation...")
    if not test_log_message_verification():
        all_tests_passed = False
    
    # Summary
    print("\n" + "=" * 80)
    if all_tests_passed:
        print("✅ ALL APA-0000619 TESTS PASSED")
        print("✅ Issue #96 fix correctly handles APA-0000619")
        print("✅ VCT cost center V-VC00048 entries will get consolidated billing")
        print("✅ APA-0000619 will no longer be incorrectly skipped")
        print("\nEXPECTED BEHAVIOR FOR APA-0000619:")
        print("- CSV converter creates consolidated entry (64.00 R-USD)")
        print("- Process japan exports keeps the consolidated entry (VCT cost center)")
        print("- Consolidated billing is created in Business Central")
        print("- No VCT responsibility entries needed (already VCT company)")
    else:
        print("❌ SOME APA-0000619 TESTS FAILED")
        print("❌ Issue #96 fix may not work correctly for APA-0000619")
    print("=" * 80)
    
    return all_tests_passed

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)