#!/usr/bin/env python3
"""
Test VCT Entries with Original CSV Converter

This test verifies that the VCT entries consolidation issue is resolved
when using the original csv_to_json_converter.py instead of the unified converter.

The test checks:
1. Charset conversion generates correct headers for original converter
2. Original converter processes VCT entries correctly
3. No consolidation issues occur
4. All entries are processed individually as expected
"""

import os
import sys
import tempfile
import json
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from core.charset_converter import convert_file as convert_charset, detect_encoding
from core.csv_to_json_converter import convert_csv_to_json

def create_test_csv_with_corrupted_headers():
    """Create a test CSV file with corrupted headers that need charset conversion."""
    # Simulate corrupted headers that would be generated by encoding issues
    corrupted_content = """voucher_no,document_date,external_doc,description,debit_account,debit_amount,debit_currency,credit_account,credit_amount,credit_currency,department,applicant,vendor,receipt_note,free_field,remarks
V-VC00048,2024/01/15,EXT001,Test VCT Entry,1110,1000,JPY,V-VC00048,1000,JPY,VCT.1234,APP001,V-VC00048,Receipt Note 1,Free Field 1,Remarks 1
V-VC00048,2024/01/15,EXT002,Test VCT Entry 2,1120,2000,JPY,V-VC00048,2000,JPY,VCT.1234,APP002,V-VC00048,Receipt Note 2,Free Field 2,Remarks 2
V-VC00049,2024/01/16,EXT003,Test VCT Entry 3,1130,1500,JPY,V-VC00049,1500,JPY,VCT.5678,APP003,V-VC00049,Receipt Note 3,Free Field 3,Remarks 3"""
    
    return corrupted_content

def test_charset_conversion_headers():
    """Test that charset conversion generates correct headers for original converter."""
    print("Testing charset conversion header generation...")
    
    # Create temporary input file with corrupted headers
    with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False, encoding='utf-8') as temp_input:
        temp_input.write(create_test_csv_with_corrupted_headers())
        temp_input_path = temp_input.name
    
    try:
        # Create temporary output file
        temp_output_path = temp_input_path.replace('.csv', '_utf8.csv')
        
        # Convert charset (this should trigger header replacement)
        encodings_to_try = ['utf-8']  # Force UTF-8 to trigger header replacement logic
        success = convert_charset(temp_input_path, temp_output_path, encodings_to_try)
        
        if not success:
            print("❌ Charset conversion failed")
            return False
        
        # Read the converted file and check headers
        with open(temp_output_path, 'r', encoding='utf-8') as f:
            converted_content = f.read()
        
        lines = converted_content.strip().split('\n')
        if not lines:
            print("❌ No content in converted file")
            return False
        
        header_line = lines[0]
        print(f"Generated headers: {header_line}")
        
        # Check if complex headers are generated
        expected_headers = [
            "伝票No.", "仕訳日", "申請日", "仕訳データ生成日", "Receipt/Invoice Note(明細)", 
            "フリー２(明細)", "備考", "Note(明細)", "Receipt/Invoice #(明細)", "勘定奉行：伝票区切", 
            "G/L Account", "借方：勘定科目：会計連携項目", "借方：補助科目：会計連携項目", 
            "換算前額", "単位", "借方：負担部門：会計連携項目", "申請者CD/支払先CD", "支払先CD", 
            "フリー２(明細)", "借方：負担部門コード", "貸方：勘定科目：会計連携項目", 
            "貸方：補助科目：会計連携項目", "Remarks"
        ]
        
        # Check if key headers are present
        key_headers_present = [
            "伝票No." in header_line,
            "仕訳日" in header_line,
            "借方：勘定科目：会計連携項目" in header_line,
            "申請者CD/支払先CD" in header_line,
            "支払先CD" in header_line
        ]
        
        if all(key_headers_present):
            print("✅ Charset conversion generates correct complex headers")
            return True, temp_output_path
        else:
            print("❌ Charset conversion did not generate expected complex headers")
            print(f"Missing headers check: {key_headers_present}")
            return False, None
            
    except Exception as e:
        print(f"❌ Error during charset conversion test: {str(e)}")
        return False, None
    finally:
        # Clean up
        if os.path.exists(temp_input_path):
            os.remove(temp_input_path)

def test_original_converter_processing(csv_file_path):
    """Test that original converter processes the CSV correctly."""
    print("Testing original CSV converter processing...")
    
    try:
        # Create temporary JSON output file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as temp_json:
            temp_json_path = temp_json.name
        
        # Convert CSV to JSON using original converter
        entry_count = convert_csv_to_json(
            csv_file_path,
            temp_json_path,
            max_desc_length=100,
            fix_line_breaks=True,
            line_break_replacement=' '
        )
        
        print(f"Original converter processed {entry_count} entries")
        
        # Read and analyze the JSON output
        with open(temp_json_path, 'r', encoding='utf-8') as f:
            entries = json.load(f)
        
        print(f"JSON contains {len(entries)} entries")
        
        # Analyze entries for VCT-specific issues
        vct_entries = [entry for entry in entries if 'V-VC' in str(entry.get('voucher_no', ''))]
        print(f"Found {len(vct_entries)} VCT entries")
        
        # Check for consolidation issues
        consolidation_issues = []
        for entry in vct_entries:
            # Check if entry has consolidation markers
            if entry.get('credit', {}).get('consolidated', False):
                consolidation_issues.append(f"Entry {entry.get('voucher_no')} is marked as consolidated")
            
            # Check for missing required fields
            if not entry.get('voucher_no'):
                consolidation_issues.append("Entry missing voucher_no")
            
            if not entry.get('credit', {}).get('vendor_code'):
                consolidation_issues.append(f"Entry {entry.get('voucher_no')} missing vendor_code")
        
        if consolidation_issues:
            print("❌ Found consolidation issues:")
            for issue in consolidation_issues:
                print(f"  - {issue}")
            return False
        else:
            print("✅ No consolidation issues found")
            print("✅ Original converter processes VCT entries correctly")
            return True
            
    except Exception as e:
        print(f"❌ Error during original converter test: {str(e)}")
        return False
    finally:
        # Clean up
        if 'temp_json_path' in locals() and os.path.exists(temp_json_path):
            os.remove(temp_json_path)

def test_run_importer_integration():
    """Test that run_importer.py works correctly with the original converter."""
    print("Testing run_importer.py integration...")
    
    try:
        # Create a test CSV file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False, encoding='utf-8') as temp_csv:
            temp_csv.write(create_test_csv_with_corrupted_headers())
            temp_csv_path = temp_csv.name
        
        # Create temporary JSON output
        temp_json_path = temp_csv_path.replace('.csv', '.json')
        
        # Import run_importer and test its main components
        from run_importer import main as run_importer_main
        import argparse
        
        # Simulate command line arguments
        test_args = [
            temp_csv_path,
            '--output-json', temp_json_path,
            '--skip-import'  # Skip ERP import for testing
        ]
        
        # Save original sys.argv
        original_argv = sys.argv
        
        try:
            # Set test arguments
            sys.argv = ['run_importer.py'] + test_args
            
            # Run the importer
            run_importer_main()
            
            # Check if JSON file was created
            if os.path.exists(temp_json_path):
                with open(temp_json_path, 'r', encoding='utf-8') as f:
                    entries = json.load(f)
                
                print(f"✅ run_importer.py successfully processed {len(entries)} entries")
                return True
            else:
                print("❌ run_importer.py did not create JSON output file")
                return False
                
        finally:
            # Restore original sys.argv
            sys.argv = original_argv
            
    except Exception as e:
        print(f"❌ Error during run_importer integration test: {str(e)}")
        return False
    finally:
        # Clean up
        if 'temp_csv_path' in locals() and os.path.exists(temp_csv_path):
            os.remove(temp_csv_path)
        if 'temp_json_path' in locals() and os.path.exists(temp_json_path):
            os.remove(temp_json_path)

def main():
    """Run all tests to verify VCT entries consolidation issue is fixed."""
    print("=" * 60)
    print("VCT Entries Original Converter Fix Verification")
    print("=" * 60)
    
    all_tests_passed = True
    
    # Test 1: Charset conversion headers
    print("\n1. Testing charset conversion header generation...")
    header_test_result, converted_csv_path = test_charset_conversion_headers()
    if not header_test_result:
        all_tests_passed = False
        converted_csv_path = None
    
    # Test 2: Original converter processing
    if converted_csv_path:
        print("\n2. Testing original converter processing...")
        converter_test_result = test_original_converter_processing(converted_csv_path)
        if not converter_test_result:
            all_tests_passed = False
        
        # Clean up converted file
        if os.path.exists(converted_csv_path):
            os.remove(converted_csv_path)
    else:
        print("\n2. Skipping original converter test due to charset conversion failure")
        all_tests_passed = False
    
    # Test 3: run_importer integration
    print("\n3. Testing run_importer.py integration...")
    integration_test_result = test_run_importer_integration()
    if not integration_test_result:
        all_tests_passed = False
    
    # Summary
    print("\n" + "=" * 60)
    if all_tests_passed:
        print("✅ ALL TESTS PASSED")
        print("✅ VCT entries consolidation issue is FIXED")
        print("✅ Original converter integration is working correctly")
    else:
        print("❌ SOME TESTS FAILED")
        print("❌ VCT entries consolidation issue may still exist")
    print("=" * 60)
    
    return all_tests_passed

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
